### ISSUE TITLE
Addition of ipython to compass environment

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Tools#305]
@xylar, happy too add a PR to include `ipython` in the compass environment: https://github.com/MPAS-Dev/MPAS-Tools/blob/master/compass/meta.yaml#L32

This will help with development.  May also want to consider including juypter too to get broader use.

**Comment by xylar** [comment]
@pwolfram, I don't mind adding `ipython` and `jupyter` to the `compass` environment.  In general, let's try to limit the environment to tools directly needed to run the scripts in COMPASS, rather than things that would be convenient to have while developing COMPASS.  

In my view, this isn't meant to be a catch-all environment like E3SM-Unified and I don't want it to become part of workflows outside of just setting up and running COMPASS test cases because this increases the likelihood that removing old versions breaks people's workflows.

**Comment by pwolfram** [comment]
I agree, just wanted some type of easy to access way to diagnose bugs in compass based on capabilities needed for scripts in compass.

Should I add it to that file or is there a better way to proceed?

**Comment by xylar** [comment]
This issue is fine.  I'll include it in #303 later this week.
